script:
  - rm -rf public || exit 0
  - ./binaries/hugo -s site/ -d ../public

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
