script:
  # Cleans out any possible old public directories -- just to be sure
  - rm -rf public || exit 0
  # Builds the site into the public dir
  - ./binaries/hugo -s site/ -d ../public

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
